spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: order_user
    password: ordere_password
  flyway:
    schemas: order_management
    default-schema: order_management
    create-schemas: true
    baseline-on-migrate: true
